sudo: true # XXX: see https://github.com/travis-ci/travis-ci/issues/9033
language: generic
dist: focal

env:
  # C++11
  - CXX=g++     BUILD_TYPE=Debug    COVERAGE=OFF STANDARD=11
  - CXX=g++     BUILD_TYPE=Release  COVERAGE=OFF STANDARD=11
  - CXX=clang++ BUILD_TYPE=Debug    COVERAGE=OFF STANDARD=11
  - CXX=clang++ BUILD_TYPE=Release  COVERAGE=OFF STANDARD=11
  # C++14
  - CXX=g++     BUILD_TYPE=Debug    COVERAGE=OFF STANDARD=14
  - CXX=g++     BUILD_TYPE=Release  COVERAGE=OFF STANDARD=14
  - CXX=clang++ BUILD_TYPE=Debug    COVERAGE=OFF STANDARD=14
  - CXX=clang++ BUILD_TYPE=Release  COVERAGE=OFF STANDARD=14
  # C++17 and coverage
  - CXX=g++     BUILD_TYPE=Debug    COVERAGE=ON  STANDARD=17
  - CXX=g++     BUILD_TYPE=Release  COVERAGE=OFF STANDARD=17
  - CXX=clang++ BUILD_TYPE=Debug    COVERAGE=OFF STANDARD=17
  - CXX=clang++ BUILD_TYPE=Release  COVERAGE=OFF STANDARD=17

script:
  - cmake -DCOOL_BUILD_TEST=ON -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOOL_TEST_COVERAGE=$COVERAGE -DCOOL_TEST_STANDARD=$STANDARD -H. -Bbuild
  - cmake --build build/ -- -j2 VERBOSE=1
  - cmake --build build/ --target test -- ARGS="-j2 -VV"

after_success:
  - if test "$COVERAGE" == "ON"; then bash <(curl -s https://codecov.io/bash) -x $(which gcov); fi
