sudo: true # XXX: see https://github.com/travis-ci/travis-ci/issues/9033
language: generic
dist: trusty

env:
  - CXX=g++ BUILD_TYPE=Debug COVERAGE=ON
  - CXX=g++ BUILD_TYPE=Release COVERAGE=OFF
  - CXX=clang++ BUILD_TYPE=Debug COVERAGE=OFF
  - CXX=clang++ BUILD_TYPE=Release COVERAGE=OFF

script:
  - cmake -DCOOL_BUILD_TEST=ON -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOOL_TEST_COVERAGE=$COVERAGE -H. -B build
  - cmake --build build/ -- -j2 VERBOSE=1
  - cmake --build build/ --target test -- ARGS="-j2 -VV"

after_success:
  - if test "$COVERAGE" == "ON"; then bash <(curl -s https://codecov.io/bash) -x $(which gcov); fi
