name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test C++${{ matrix.cpp_standard }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cpp_standard: [11, 14, 17, 20, 23]

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.11'

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCOOL_BUILD_TEST=ON -DCOOL_TEST_STANDARD=${{ matrix.cpp_standard }} -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Test
      run: ./build/test/cool_test_suite