name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.14'

    - name: Test all C++ standards
      run: |
        for std in 11 14 17 20 23; do
          echo "Testing C++$std"
          rm -rf build
          mkdir -p build
          cd build
          cmake .. -DCOOL_BUILD_TEST=ON -DCOOL_TEST_STANDARD=$std -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ./test/cool_test_suite
          cd ..
        done

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Cool Library ${{ steps.get_version.outputs.VERSION }}
        body: |
          Cool Library ${{ steps.get_version.outputs.VERSION }}
          
          A collection of self-contained C++ utilities for common programming tasks.
          
          ## Features
          - **colony**: Unordered container with stable memory addresses
          - **channel**: Go-like channels for thread communication  
          - **thread_pool**: Thread pool with job queuing
          - **defer**: Deferred execution of statements
          - **compose**: Lambda composition (C++17+)
          - **enum_map**: Enumeration-based mapping (C++17+)
          - **indices**: Safer range-based for loops
          - **ccreate**: Legacy C data type wrapper
          - **progress**: Progress tracking utility
          
          ## Compatibility
          - Supports C++11 through C++23
          - Header-only library
          - Requires CMake 3.14+
        draft: false
        prerelease: false